### ISSUE TITLE
postgresql 데드락 이슈

### ISSUE THREAD

**Issue by ghdwlsrl3229** [skku-npc/skku-coding-platform#125]
드물게 Postgresql에서 deadlock이 걸리는 것을 확인했습니다. 
데드락이 발생하지 않도록 로직을 수정할 필요가 있을 것 같습니다.

https://www.notion.so/postgres-Deadlock-dcd1387ab8014c3fb3302084d3438cb2

**Comment by dotoleeoak** [comment]
#9와 같이 확인 필요
