### ISSUE TITLE
Problem에 TestCase가 없을 때 Edit Problem하면 오류 발생

### ISSUE THREAD

**Issue by jimin9038** [skku-npc/skku-coding-platform#130]
Create Problem에서 testcase를 하나도 추가하지 않고 저장한 후 Problem을 불러오면 admin/testcase api에서 405 에러가 발생합니다.
![image](https://user-images.githubusercontent.com/73051219/123672880-ce14a000-d87a-11eb-836b-7e64df83e96f.png)
![image](https://user-images.githubusercontent.com/73051219/123672896-d240bd80-d87a-11eb-917c-dbe084b2c3fc.png)

**Comment by dotoleeoak** [comment]
frontend 보다는 backend 문제 같습니다
@ghdwlsrl3229 확인 부탁드려요

**Comment by dotoleeoak** [comment]
@joft-ware 시간 괜찮으시면 같이 확인 부탁드리겠습니다

**Comment by ghdwlsrl3229** [comment]
@jimin9038 제 로컬에서는 해당 이슈가 재현이 안됩니다.
혹시 coding-platform 컨테이너에 최신 백엔드 파일들을 복사한 후에 다시 확인해주실 수 있으신가요? (백엔드 반영 방법은 skku-coding-platform/backend 경로에서 `docker cp . coding-platform:/app` 을 하고 coding-platform 컨테이너를 restart해주시면 됩니다.)

**Comment by 22222bh** [comment]
@ghdwlsrl3229 @joft-ware 
![image](https://user-images.githubusercontent.com/74390587/123795219-bdb60100-d91e-11eb-8b94-4a920a48c9b6.png)
재훈님 말씀처럼 이렇게 테스트 케이스가 빈 상태에서는 저장이 안되지만 이 상태에서 우측에 delete를 누르면 테케가 없어도 저장이 됩니다.
그래서 이 부분을 수정을 해야 하는데, 진기님 일단 지금 하고 계신 db 관련은 잠깐 미뤄두고 목요일까지 가능 하실까요?

**Comment by dotoleeoak** [comment]
지금 재훈님 급한거 없으면 재훈님께서 하는게 낫지 않을까요?

**Comment by 22222bh** [comment]
> 지금 재훈님 급한거 없으면 재훈님께서 하는게 낫지 않을까요?

백엔드 전원이 db 펜딩 이슈 해결하는 중이고 진기님이 저 테케 수정하는 부분 하셨어서 진기님한테 요청 드립니당

**Comment by ghdwlsrl3229** [comment]
네 제가 해당 이슈 수정하겠습니다.
