### ISSUE TITLE
디자인 수정 필요

### ISSUE THREAD

**Issue by Jeongcc** [skku-npc/skku-coding-platform#135]
[Contest]
- 가로폭 notice 만큼 줄이는 게 보기 좋을 듯
- Contest 클릭 시 Problem List 위에 Contest Description이 나오도록 수정하기
![image](https://user-images.githubusercontent.com/46365350/123998828-d4d31c80-da0c-11eb-9427-ab676a2f740b.png)

[Contest List]
- 가로폭 notice 만큼 줄이는 게 보기 좋을 듯

[Problem List]
- 가로폭 notice 만큼 줄이는 게 보기 좋을 듯

[Notice List]
- 가로폭 notice 만큼 줄이는 게 보기 좋을 듯

* Notice의 가로폭
![image](https://user-images.githubusercontent.com/46365350/123999124-1fed2f80-da0d-11eb-88dd-ed0183c750bd.png)

**Comment by Jeongcc** [comment]
[Admin - Create Problem]
![image](https://user-images.githubusercontent.com/46365350/124636967-1dcf1900-dec4-11eb-9d07-fce2f2ce245e.png)
에디터 버튼의 색상 수정하기 (회색 계열이 좋을 듯)

**Comment by DailyPS** [comment]
@Jeongcc 에디터 버튼의 색상이 회색계열이라는 게 선택되었을 때 검은색이 아니라 회색이 되게끔 하는 걸 말씀하시는 건가요?
