### ISSUE TITLE
Ended Contest Problem에서 'Contest has ended' 에러창이 뜨지 않는 문제

### ISSUE THREAD

**Issue by minseo999** [skku-npc/skku-coding-platform#173]
해당 contest의 status가 ended일때 종료된 contest임을 알리는 알림창이 정상적으로 동작하지 않습니다.

oj/views/problem.vue
![image](https://user-images.githubusercontent.com/76725982/126036327-b6bcaa0f-059f-47cb-8320-dd59e6d2377b.png)

**Comment by dotoleeoak** [comment]
`this.$error` 메서드는 제대로 동작 하나요?

**Comment by minseo999** [comment]
![image](https://user-images.githubusercontent.com/76725982/126037958-6f7382c3-3a18-4fb7-9722-a19ef2c3007b.png)
아니요 콘솔창에서 에러가 확인됩니다

**Comment by jimin9038** [comment]
this.$error에서 this가 contestEnded를 지칭해서 undefined로 인식되네요. 
https://stackoverflow.com/questions/42242682/this-is-undefined-in-vue-js-watcher 
watcher에서는 arrow function 을 사용하면 안된다고 합니다.

**Comment by jimin9038** [comment]
`contestEnded: function () {
      console.log('This is notice!')
      this.$error('Contest has ended :<')
    }`
    로 바꾸면 정상작동됩니다.
