### ISSUE TITLE
`/deep/` syntax is deprecated

### ISSUE THREAD

**Issue by jimin9038** [skku-npc/skku-coding-platform#184]
`/deep/` syntax는 `dart-sass` 에서는 이미 사용이 불가능하고, `node-sass`에서는 deprecated 상태입니다. (현재 node-sass 사용 중)

https://stackoverflow.com/questions/48032006/how-do-i-use-deep-or-or-v-deep-in-vue-js 에 따라
`/deep` syntax를 `::v-deep` syntax로 변경하면 될 것 같습니다.

(`node-sass`는 deprecated된 상태고, `dart-sass`로 migrating할 때 고쳐야하므로 미리 해두면 좋을 것 같네요.)

**Comment by dotoleeoak** [comment]
`::v-deep`을 쓰는 것보단 아예 deep 문법 자체를 가능하면 쓰지 않는 것이 좋을 것 같습니다. 전에 deep을 사용항 이유가 bootstrap에 정의된 style을 overriding하려고 한건데, bootstrap의 일부 css만 포함시키거나(예: grid 시스템만 사용 or bootstrap-vue component만 사용) class 이름을 바꾸는 등의 방법으로 deep 사용을 자제하는 것이 좋겠습니다.

**Comment by jimin9038** [comment]
Vue 3 & typescript enhancement #180 와 같이 처리할 예정
