### ISSUE TITLE
JudgeStatus를 눌러도 에러에 대한 정보가 나오지 않는 이슈

### ISSUE THREAD

**Issue by 22222bh** [skku-npc/skku-coding-platform#187]
ex. compile error 발생 시, 관련 에러메시지를 띄워줬었는데 현재 작동하지 않음

![image](https://user-images.githubusercontent.com/74390587/126962422-09c84f29-1fee-4099-854c-e291b0d824e6.png)

**Comment by jimin9038** [comment]
이 부분 Wrong answer나 맞았을 경우에는 Submission detail이 잘 작동하지만 Compile error 발생시에만 작동하지 않습니다.
submission api에서 Compile error 시 data.info가 비어있는 상태로 response가 와서 작동하지 않습니다. 
프론트엔드에서 고치면 될 것 같습니다.
