### ISSUE TITLE
문제 푸는 페이지에서 문제에 대한 정보(시간, 메모리 제한 등)가 충분히 제공되지 않음

### ISSUE THREAD

**Issue by 22222bh** [skku-npc/skku-coding-platform#188]
sample input, output만 나오지 문제 푸는데 필요한 시간 제한, 메모리 제한 등의 정보가 나오지 않음.

아래 사진은 백준의 문제 세팅 사진

![image](https://user-images.githubusercontent.com/74390587/126962913-423030b7-0df8-4b7b-9649-4fe4dac61b6f.png)

**Comment by 22222bh** [comment]
근데 저는 이런 ps 플랫폼을 백준만 사용했어서 당연히 시간, 메모리 제한 등은 나와야 한다고 생각했었는데 프로그래머스 들어가보니까 여기도 안알려주는 것 같네요. 보통은 어떤식으로 진행하나요?

**Comment by jimin9038** [comment]
타 플랫폼의 경우에는 10초 제한이나 1분 제한이 걸려있는 것 같은데, 이건 조정할 수 있는 것 같습니다.
problem 페이지 Description에 메모리 제한이나 시간 제한을 추가할까 하는데 다른 분들은 어떻게 생각하시나요?

**Comment by dotoleeoak** [comment]
qduoj.com
https://github.com/QingdaoU/OnlineJudge#frontend

우리 프로젝트의 기반인 QingdaoU OJ를 보면 이미 메모리, 시간 제한 등은 구현되어있습니다. 디자인 리뉴얼 과정에서 누락된 것이니 당연히 추가하는 것이 맞다고 봅니다.

**Comment by jimin9038** [comment]
알겠습니다.
