### ISSUE TITLE
비밀번호 초기화 시 이메일 미발송

### ISSUE THREAD

**Issue by dotoleeoak** [skku-npc/skku-coding-platform#19]
이메일 발송 원리 확인해보기

**Comment by Just4Study** [comment]
현재 npc.skku.edu의 SMTP 설정이 되어 있는지 궁금합니다.

**Comment by Jeongcc** [comment]
설정이 안 되어있어서 우선 제 메일로 SMTP 설정했습니다. NPC 메일 계정 파서 수정할 예정입니다.

**Comment by Just4Study** [comment]
> 설정이 안 되어있어서 우선 제 메일로 SMTP 설정했습니다. NPC 메일 계정 파서 수정할 예정입니다.

현재 로컬환경에서 admin 접근이 안되서 그런데, npc.skku.edu을 admin으로 접속시 smtp 설정이 가능한가요??

**Comment by Just4Study** [comment]
Admin에서 SMTP Config 설정만 해주면 정상적으로 이메일 발송이 되는 것 같습니다.
