### ISSUE TITLE
Monospaced font is not applied to code

### ISSUE THREAD

**Issue by dotoleeoak** [skku-npc/skku-coding-platform#191]
CodeMirror.vue에 monospaced font가 아니라 Manrope font가 적용되어있다.

![image](https://user-images.githubusercontent.com/19747913/127075353-e5eed5d9-3832-464d-866e-c60d682bb929.png)

**Comment by jimin9038** [comment]
++ 사이드바를 통해 Submission Detail modal을 띄울 경우 제출한 소스 코드가 잘 보이는데 Reset 버튼 왼쪽의 제출 결과 를 눌러 modal을 띄우면 소스 코드가 깨져서 보이는 문제 해결 

![image](https://user-images.githubusercontent.com/73051219/127091110-2b904dd6-0283-4cc5-b2d2-ea6ae853be7a.png)
