### ISSUE TITLE
Submission Detail modal 소스코드 깨짐

### ISSUE THREAD

**Issue by Jeongcc** [skku-npc/skku-coding-platform#194]
![image](https://user-images.githubusercontent.com/46365350/127503309-91779772-5526-4bd4-b8f6-9fd5a0f99022.png)

![image](https://user-images.githubusercontent.com/46365350/127503332-51985d05-313b-44d4-bcc5-47a7d34e7b4d.png)

사이드바를 통해 `Submission Detail modal`을 띄울 경우 제출한 소스 코드가 잘 보이는데 
Reset 버튼 왼쪽의 제출 결과를 눌러 `Submission Detail modal`을 띄우면 소스 코드가 깨져서 보임

소스 코드 영역을 클릭해야 소스 코드가 나오고, 그것도 깨져서 보임

**Comment by DailyPS** [comment]
#191 에 같이 언급되어 있습니다

**Comment by Jeongcc** [comment]
아아 감사합니다
