### ISSUE TITLE
Admin - Problem Page Testcase 확인/수정/삭제 기능 지원

### ISSUE THREAD

**Issue by Jeongcc** [skku-npc/skku-coding-platform#195]
![image](https://user-images.githubusercontent.com/46365350/127504756-ad5e9aba-ac97-4a10-83f5-fbf489c206fa.png)

손으로 일일이 입력한 테스트케이스들이 파일로 변환되서 저장되고,
각 테케의 정보를 보거나 삭제, 수정이 불가능해서 사용하기 불편한 문제.

**Comment by cranemont** [comment]
Typo 때문에 렌더링이 안되는 문제였습니다. parameterId 오류 고치면서 같이 해결했습니다.
