### ISSUE TITLE
Code Template 설정시 무조건 컴파일 에러 발생

### ISSUE THREAD

**Issue by jimin9038** [skku-npc/skku-coding-platform#197]
Admin에서 Code Template 설정하면 oj에서 문제 맞게 제출해도 컴파일 에러 발생 문제 발생

이렇게 
![image](https://user-images.githubusercontent.com/73051219/127603802-a0d76a30-1401-4ade-93f4-ca56eab42768.png)
코드 템플릿을 설정한 문제를 만들면 oj에서 맞게 제출해도 
![image](https://user-images.githubusercontent.com/73051219/127603905-fdcf6b21-35cb-4a5b-80b4-6a910fb91ca7.png)
다음과 같이 컴파일 에러가 뜹니다 
코드 템플릿을 설정하지 않고 똑같이 제출하면 Accepted가 뜹니다. 
![image](https://user-images.githubusercontent.com/73051219/127603942-06ba14fe-d3f1-412a-9e6a-1b2fc8431b24.png)

**Comment by dotoleeoak** [comment]
Compile error 내용은 뭔가요?

**Comment by jimin9038** [comment]
![image](https://user-images.githubusercontent.com/73051219/127604504-cae7c63d-5042-4ee5-9b56-e640770abfea.png)
main redefinition입니다. 
![image](https://user-images.githubusercontent.com/73051219/127604602-114c0871-c53f-40c4-929a-c0b0ec2dedfe.png)
API request와 response에 main redefinition이 없는 걸 보니 아마 채점 과정에서 문제가 있는가 봅니다.

**Comment by dotoleeoak** [comment]
템플릿 설정한 경우랑 설정 안한 경우 request에 코드 비교해보세요

**Comment by jimin9038** [comment]
설정했을 때 Request
![image](https://user-images.githubusercontent.com/73051219/127605797-9a0ab59c-0c48-465a-bcc3-ddb99c61ce99.png)
설정 안했을 때 Request
![image](https://user-images.githubusercontent.com/73051219/127605865-52f727de-e1c4-47f5-9d3a-bea5abc9e9b8.png)

템플릿 설정한 경우랑 설정 안한 경우 Request 같습니다 
이걸 말하는거죠?
