### ISSUE TITLE
Setup reverse proxy to host machine

### ISSUE THREAD

**Issue by cranemont** [skku-npc/skku-coding-platform#240]
개발, 배포 서버가 하나로 운영되고 있어 다음과 같은 문제점들이 발생합니다.

- 동시에 개발, 배포 컨테이너 중 하나만 사용 가능합니다. 현재는 대회 때만 배포 버전이 필요하여 문제가 없지만 강의지원플랫폼이나 추후 지속적인 서비스 사용을 고려했을 때 배포 컨테이너를 유지할 수 있어야 합니다.

- 컨테이너에 mount된 폴더가 흩어져 있어 지난 대회의 데이터 유지 및 관리가 제대로 되고 있지 않습니다.

서버 자체에 reverse proxy를 추가로 적용하여 분리하면 위 문제들이 어느 정도 해결될 것으로 보입니다.

**Comment by dotoleeoak** [comment]
이슈 내용이 잘 이해가 안되는데, 포트가 겹쳐서 컨테이너를 동시에 못 올리는 문제를 말쑴하시는 건가요?

**Comment by cranemont** [comment]
네 맞습니다

**Comment by dotoleeoak** [comment]
@cranemont 그러면 개발용 컨테이너는 다른 포트로 띄우면 되지 않나요?

**Comment by cranemont** [comment]
@dotoleeoak 그 방법도 고려해봤는데 포트를 추가로 개방하고 관리하는 것이 보안 리스크가 될 수 있다고 생각했습니다.
[](https://www.bitsight.com/blog/open-port-vulnerabilities-whats-the-big-deal)
저번에 교수님과 면담했을 때 슬랙을 대체할 mattermost, 팀 소개 페이지 등 여러 도메인을 운영할 수 있으면 좋겠다는 얘기가 나왔고, 장기적으로 봤을 때 최소한의 포트로 reverse proxy를 사용하는 것이 좋다고 생각했습니다.

**Comment by cranemont** [comment]
서버를 추가하게 되어 필요하지 않아 close합니다.
