### ISSUE TITLE
bug: `LectureBookmark` component does not exist

### ISSUE THREAD

**Issue by dotoleeoak** [skku-npc/skku-coding-platform#280]
`frontend/src/pages/oj/router/routes.js` 파일에서 routing하는 `LectureBookmark` component가 제대로 import 되지 않아 확인해보니 해당 이름을 가진 component가 없어요... 🤔

**Comment by jimin9038** [comment]
tailwind CSS PR에 포함해서 들어갈 예정입니다.
`LectureBookmark`는 존재하지 않는 컴포넌트로, `routes.js` 에서 삭제될 예정입니다.
