### ISSUE TITLE
UI 좌우폭 조절

### ISSUE THREAD

**Issue by dotoleeoak** [skku-npc/skku-coding-platform#4]
문제 설명과 같이, 전반적인 UI의 좌우폭을 적당하게 줄일 것.
예: `width: min(70%, 100px)`

![image](https://user-images.githubusercontent.com/19747913/103459924-b2aa5b80-4d55-11eb-85e0-8e0e30f76e67.png)

**Comment by illuminoplanet** [comment]
귀찮아

**Comment by dotoleeoak** [comment]
@illuminoplanet 일해라 주영

**Comment by dotoleeoak** [comment]
디자인이 변경됨에 따라 적용하지 않음.
