### ISSUE TITLE
Django 3.2 Upgrade & Apply ASGI

### ISSUE THREAD

**Issue by Jeongcc** [skku-npc/skku-coding-platform#70]
현재 프로젝트의 Django 버전은 2.2, 3.1로 업그레이드하기

https://docs.djangoproject.com/en/3.1/howto/upgrade-version/

*Django는 3.1부터 비동기를 더 지원하기 때문에, dramatiq 제거해보기

**Comment by dotoleeoak** [comment]
[ASGI와 WSGI 분석(Analysis of ASGI and WSGI)](https://nitro04.blogspot.com/2020/01/django-python-asgi-wsgi-analysis-of.html)
현재 Gunicorn이 WSGI로 동작 중인데, ASGI가 WSGI에 비동기 지원을 추가한 상위 호환으로 알려져있음.
Django 업그레이드 시 ASGI 적용할 것

> dramatiq는 background process를 위한 것으로, Django만으로 대체 가능한지는 더 알아보기...

**Comment by dotoleeoak** [comment]
- gunicorn => uvicorn으로 대체
- dramatiq => 아직 모르지만 안 써도 될 듯...?

**Comment by dotoleeoak** [comment]
`urls.py`에 `url()` => `path()`로 변경하기
