### ISSUE TITLE
Footer 하단에 공백 추가

### ISSUE THREAD

**Issue by dotoleeoak** [skku-npc/skku-coding-platform#72]
Footer 맨 아래 공백(margin) 추가하기

![image](https://user-images.githubusercontent.com/19747913/111154273-6477cb00-85d6-11eb-9235-1f886d22596d.png)

**Comment by 22222bh** [comment]
아래 공백의 푸른 색은 잘 보이게 일부러 넣으신건가요 아니면 푸른 색을 추가하라는 건가요?

**Comment by dotoleeoak** [comment]
@22222bh 푸른 색은 그냥 윈도우에 상태표시줄 같이 캡처된거야
